pkgchanges: use case instead of ifs

diff --git a/bin/pkgchanges b/bin/pkgchanges
--- a/bin/pkgchanges
+++ b/bin/pkgchanges
@@ -1,17 +1,20 @@
 #!/bin/sh
+_usage(){
+	echo "Usage: $(basename $0) [core/extra/community/multilib] package"
+}
+
 if [ $# -ne 2 ]; then
-	echo "usage: pkgchanges [core/extra/community/multilib] [package]"
+	_usage
 	exit 1
 fi
 
-if [ $1 == "core" ] || [ $1 == "extra" ]; then
-	REPO="packages"
-elif [ $1 == "community" ] || [ $1 == "multilib" ]; then
-	REPO="community"
-else
-	echo "error: $1 is not a valid repository"
-	exit 1
-fi
+case $1 in
+	core)      REPO='packages' ;;
+	extra)     REPO='packages' ;;
+	community) REPO='community' ;;
+	multilib)  REPO='community' ;;
+	*)         echo "error: not a valid repository"; exit 1 ;;
+esac
 
 xdg-open "https://projects.archlinux.org/svntogit/$REPO.git/log/trunk?h=packages/$2"
 
