bin/x-w-o: Fix wrong dependency check

diff --git a/bin/.bin/xdg-what-opens b/bin/.bin/xdg-what-opens
--- a/bin/.bin/xdg-what-opens
+++ b/bin/.bin/xdg-what-opens
@@ -15,8 +15,8 @@ EOF
 	exit 1
 fi
 
-if ! ( hash xdg-utils 2>/dev/null ); then
-	echo "Error: This script requires xdg-utils."
+if ! ( hash xdg-mime 2>/dev/null ); then
+	echo "Error: This script requires xdg-mime from xdg-utils."
 	exit 1
 fi
 
